---
# Clone a codebase from git and install its dependencies

- name: Clone codebase repository
  git:
    repo: "{{ codebase.repo }}"
    dest: "{{ project.path }}/codebase"
    version: "{{ codebase.version }}"
    update: no
  when: codebase.repo != ""
