---
# Clone a codebase from git and install its dependencies

- name: Clone codebase repository
  git:
    repo: "{{ codebase_repo }}"
    dest: "{{ project_path }}/codebase"
    version: "{{ codebase_version }}"
    update: no

- name: Fix codebase permissions
  shell: docker-compose exec -u root php chown -R wodby:wodby /var/www/html
  args:
    chdir: "{{ project_path }}"

- name: Install codebase dependencies with Composer
  shell: docker-compose exec php composer install
  args:
    chdir: "{{ project_path }}"
