---
# Create .env and docker-compose.override.yml templates

- name: Create .env from template
  template:
    src: .env.j2
    dest: "{{ project_path }}/.env"
    owner: root
    group: root
    mode: 0600

- name: Create docker-compose.override.yml from template
  template:
    src: docker-compose.override.yml.j2
    dest: "{{ project_path }}/docker-compose.override.yml"
    owner: root
    group: root
