---
# Create WP configuration file to establish database connection.

- name: Create WP Config
  shell: |
    docker-compose exec \
    -T php \
    wp config create \
      --dbname={{ mariadb_db_name }} \
      --dbuser={{ mariadb_user }} \
      --dbpass={{ mariadb_password }} \
      --dbhost={{ mariadb_service_name }} \
      --force
  args:
    chdir: "{{ project_path }}"
  ignore_errors: true
