---
# Download database backup object from S3 and import it into MariaDB

- name: Import database backup
  block:
    - name: Download backup from S3
      aws_s3:
        aws_access_key: "{{ spaces_access_key }}"
        aws_secret_key: "{{ spaces_secret_key }}"
        s3_url: "{{ spaces_endpoint }}"
        bucket: "{{ space_name }}"

        object: "{{ space_file_path }}"
        dest: "{{ mysqldump_file_path }}"

        encrypt: false
        rgw: true
        mode: get

    - name: Reset target database
      shell: \
        docker-compose exec \
          -T {{ mariadb_service_name }} \
          mysql \
          -u root \
          -p{{ mariadb_root_password }} \
          -e "DROP DATABASE IF EXISTS {{ mariadb_db_name }}" && \
        docker-compose exec \
          -T {{ mariadb_service_name }} \
          mysql \
          -u root \
          -p{{ mariadb_root_password }} \
          -e "CREATE DATABASE {{ mariadb_db_name }}"
      args:
        chdir: "{{ project_path }}"

    - name: Use Docker Compose to import mysqldump on the database service
      shell: |
        docker-compose exec \
          -T {{ mariadb_service_name }} \
          mysql \
          -u root \
          -p{{ mariadb_root_password }} \
          {{ mariadb_db_name }} \
          < {{ mysqldump_file_path }}
      args:
        chdir: "{{ project_path }}"
  always:
    - name: Delete temporary backup
      file:
        path: "{{ mysqldump_file_path }}"
        state: absent
