---
# tasks file for docker4wordpress

- name: Stop docker4wordpress services
  docker_service:
    project_src: "{{ project.path }}"
    state: absent
  ignore_errors: yes

- name: Clone docker4wordpress repository
  git:
    repo: "{{ docker4wordpress.repo }}"
    dest: "{{ project.path }}"
    version: "{{ docker4wordpress.version }}"
    update: no

- name: Import Codebase
  import_tasks: codebaseimport.yml
  when: codebase.repo != ''

- name: Create .env from template
  template:
    src: .env.j2
    dest: "{{ project.path }}/.env"
    owner: root
    group: root
    mode: 0600

- name: Create docker-compose.override.yml from template
  template:
    src: docker-compose.override.yml.j2
    dest: "{{ project.path }}/docker-compose.override.yml"
    owner: root
    group: root

- name: Create Traefik network
  docker_network:
    name: "{{ traefik.network }}"

- name: Copy mariadb variable to mariadb_cfg variable
  set_fact:
    mariadb_cfg: "{{ mariadb }}"

- name: Startup docker4wordpress services
  docker_service:
    project_src: "{{ project.path }}"
    state: present
    services: "{{ startup_services }}"

- name: Create WP Config
  import_tasks: createwpconfig.yml

- name: Import Database Backup
  import_tasks: dbimport.yml
  when: mysqldump_file_name != ''
