---
# tasks file for docker4wordpress

- name: Stop docker4wordpress services
  docker_service:
    project_src: "{{ project.path }}"
    state: absent
  ignore_errors: yes

- name: Clone docker4wordpress repository
  git:
    repo: "{{ docker4wordpress.repo }}"
    dest: "{{ project.path }}"
    version: "{{ docker4wordpress.version }}"
    update: no

- name: Create .env from template
  template:
    src: .env.j2
    dest: "{{ project.path }}/.env"
    owner: root
    group: root
    mode: 0600

- name: Create docker-compose.override.yml from template
  template:
    src: docker-compose.override.yml.j2
    dest: "{{ project.path }}/docker-compose.override.yml"
    owner: root
    group: root

- name: Create Traefik network
  docker_network:
    name: "{{ traefik.network }}"

- name: Startup docker4wordpress services
  docker_service:
    project_src: "{{ project.path }}"
    state: present
    services: "{{ startup_services }}"

- name: Debug Mariadb
  debug:
    msg: "{{ mariadb }}"

- name: Import Database Backup
  block:
    - name: Download Backup from S3
      aws_s3:
        aws_access_key: "{{ spaces_access_key }}"
        aws_secret_key: "{{ spaces_secret_key }}"
        s3_url: "{{ spaces_endpoint }}"
        bucket: "{{ space_name }}"

        object: "{{ space_file_path }}"
        dest: "{{ mysqldump_file_path }}"

        encrypt: false
        rgw: true
        mode: get

    - name: Use docker compose to import a mysqldump on the database service
      shell: docker-compose exec -T {{ mariadb.service_name }} mysql -u {{ mariadb.user }} -p{{ mariadb.password }} {{ mariadb.db_name }} < {{ mysqldump_file_path }}
      args:
        chdir: "{{ project.path }}"
  always:
    - name: Delete Temporary Backup
      file:
        path: "{{ mysqldump_file_path }}"
        state: absent
  when: mysqldump_file_name is defined
