---
# tasks file for docker4wordpress

- name: Initialize Environment
  import_tasks: init.yml

- name: Create Templates
  import_tasks: create_templates.yml

- name: Start Services
  import_tasks: start_services.yml

- name: Import Codebase
  import_tasks: import_codebase.yml
  when: codebase_import

- name: Import Database Backup
  import_tasks: import_database.yml
  when: mariadb_import

- name: Create Wordpress configuration file
  import_tasks: create_wpconfig.yml

- name: Restart Services
  import_tasks: restart_services.yml
